### ISSUE TITLE
Dividing by eval

### ISSUE THREAD

**Issue by ulivc** [stroblme/quantum-framework-runtime-eval#1]
https://github.com/stroblme/qiskit-circuit-runtime-eval/blob/d313389f7733694d0418700a37579cc04a51733f/qiskit-test_duration_depth.py#L35

Why are we not dividing by eval?

**Comment by stroblme** [comment]
linear scaling and only relative duration relevant (overall time heavily depends on the hardware).
should be implemented as mentioned, but the units should then better be changed to ms
